Hf sft
chenbin11200/openspg_youyou pull request #1
Opened 2024-01-18 12:45 UTC by chenbin11200

baichuan 模型 local sft完成，包括一些基础类的改动

2024-01-19 09:58 UTC, didicout requested changes

2024-01-19 09:58 UTC, didicout commented on python/nn4k/nn4k/executor/huggingface/example/decode_only_sft.json5
> +  // -- adapter model info
加个注释：以下参数都是可选的

2024-01-19 09:58 UTC, didicout commented on python/nn4k/nn4k/executor/huggingface/example/decode_only_sft.json5
> +  "nn_name": "Baichuan", //nn_name and nn_version are necessary for detect the corrent invoker or executor
应该是 (nn_name, nn_version) 和 nn_model_path 严格二选一吧？ 而不是这边 先用name和version决定了 invoker和Executor，然后用path决定了weight文件。

建议要不这边path删了，挪到 hub 里。simple hub的实现 可以读取一个配置文件（当成一个db），里面记录了 hub 里 管理的信息。

2024-01-19 09:58 UTC, didicout commented on python/nn4k/nn4k/executor/huggingface/example/decode_only_sft.json5
> +  "output_dir": "/mnt/new_nas/users/youyou/output_temp/sft_1__nolora_2", // trained model output dir
同上，要不这边只出现 output_nn_name（是否要限制只允许指定新version、不允许制定新name？）, output_nn_version；dir 都丢到hub里

2024-01-19 09:58 UTC, didicout commented on python/nn4k/nn4k/invoker/base.py
> +    def local_sft(self):
这边不能再传额外参数么？

HF 里 配置文件是 train一份、inference一份，是因为它的执行对象就是 trainer、predict之类的。  我们这边，应该区分一下 model 的配置 和 任务的配置？model 配置中，包含模型定义和初始化需要的配置（HF的ModelArguments）、以及train、inference的部分配置项的默认配置（DataTrainingArguments 等的默认配置值））；实际执行train的时候，传入需要的其他配置（DataTrainingArguments 的实例化的值）、或覆盖一些默认配置。

2024-01-22 11:17 UTC, xionghuaidong requested changes
Python 代码提交前应用 black 格式化，参考鸡饭的开发规范文档。

2024-01-22 11:17 UTC, xionghuaidong commented on python/nn4k/nn4k/consts/__init__.py
>  NN_TRUST_REMOTE_CODE_KEY = "trust_remote_code"
建议就用 device。要把 device 改成 nn_device 的话，最好把 trust_remote_code 也改成 nn_trust_remote_code。

2024-01-22 11:17 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/huggingface/base/hf_args.py
> +    input_max_length: int = field(
改成 max_input_length，与 HfLlmExecutor.inference 的 max_input_length 参数名保持一致。

2024-01-22 11:17 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/huggingface/example/task_entry.py
> +from nn4k.invoker.base import NNInvoker
nn4k 示例统一放到 python/nn4k/nn4k/examples 吧，和 python/knext/knext/examples 下已有的 kNext 示例保持目录位置一致。

2024-01-22 11:17 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/huggingface/base/hf_llm_executor.py
> +class HfLlmExecutor(LLMExecutor):
HfLlmExecutor 和 LLMExecutor 中 LLM 的大小写最好统一。

2024-01-23 06:13 UTC, chenbin11200 commented on python/nn4k/nn4k/consts/__init__.py
>  NN_TRUST_REMOTE_CODE_KEY = "trust_remote_code"
这里用device的话，会和huggingface的device冲突，开发的时候遇到了问题

2024-01-23 06:14 UTC, chenbin11200 commented on python/nn4k/nn4k/executor/huggingface/example/task_entry.py
> +from nn4k.invoker.base import NNInvoker
设计不同，这里设计不仅仅是示例，还是默认的执行参数。

2024-01-23 06:15 UTC, chenbin11200 commented on python/nn4k/nn4k/executor/huggingface/base/hf_llm_executor.py
> +class HfLlmExecutor(LLMExecutor):
不太好改了，LLM现在已经开出去做为基类了。但是还是想用camelCase

2024-01-23 09:52 UTC, chenbin11200 commented on python/nn4k/nn4k/executor/huggingface/base/hf_llm_executor.py
> +class HfLlmExecutor(LLMExecutor):
rename to HFLLM

2024-01-24 08:15 UTC, chenbin11200 commented on python/nn4k/nn4k/consts/__init__.py
>  NN_TRUST_REMOTE_CODE_KEY = "trust_remote_code"
NN_TRUST_REMOTE_CODE_KEY只会用在huggingface相关的配置中，直接从nn系列中删除了（没有被使用了）

2024-01-24 08:22 UTC, chenbin11200 commented
@didicout @xionghuaidong 都改完了，可以再看一下

2024-01-24 09:32 UTC, xionghuaidong commented
测试和配置文件里面的 input_max_length 没有一块改，别的我觉得 OK。测试可以用 https://github.com/OpenSPG/openspg/pull/104 里面加的 run_all_tests.py 跑一下。

2024-01-25 08:01 UTC, chenbin11200 commented
> 测试和配置文件里面的 input_max_length 没有一块改，别的我觉得 OK。测试可以用 [OpenSPG#104](https://github.com/OpenSPG/openspg/pull/104) 里面加的 run_all_tests.py 跑一下。

OK，测试里的我也改掉了。

2024-01-26 09:30 UTC, didicout requested changes

2024-01-26 09:30 UTC, didicout commented on python/nn4k/nn4k/utils/io/dataset_utils.py
> +    def auto_dataset(input_path, split="train", transform_fn=None, dataset_map_fn=None):
加点单测？

2024-01-29 11:27 UTC, merged